### ISSUE TITLE
Better handle missing `gcloud` binary

### ISSUE THREAD

**Issue by danopia** [AndyClausen/yarn-plugin-gcp-auth#9]
Hello, I've seen that this plugin throws an error if `gcloud` is not available:

```
➤ YN0001: │ @private-scope/my-package@npm:2.1.1: Process gcloud failed to spawn
➤ YN0001: │   Thrown Error: spawn gcloud ENOENT
```

This made sense to me at first because it indicates what is needed for `yarn install` to succeed.

However I've found that _this error breaks Dependabot_. I tested this by patching the plugin to handle the spawn failure and `return null` instead of throwing. Then Dependabot was able to create a PR for the private package again.

The downside of my patch is that there's no longer an indication of why auth didn't work if you have a laptop without `gcloud`:

```
➤ YN0041: │ @private-scope/my-package@npm:2.1.1: Invalid authentication (as an anonymous user)
```

I suspect that a warning could be logged instead, so humans can install `gcloud` while dependabot can continue on.

Let me know if I could provide any further details.

**Comment by AndyClausen** [comment]
So if I understand this correctly, dependabot breaks while trying to fetch info on your private package, right?

I'm not super happy about swallowing error messages. Have you tried setting the `ACCESS_TOKEN` env var? It should have the same effect if you provide a dummy value. Here's an [article with more info](https://docs.github.com/en/enterprise-cloud@latest/code-security/dependabot/working-with-dependabot/configuring-access-to-private-registries-for-dependabot)

Lemme know if it works or if you find a better way - could be readme-worthy :)

**Comment by AndyClausen** [comment]
Actually, scratch that, it seems like dependabot doesn't support custom environmental variables like that. The article I linked only describes using GitHub secrets.

I'm not sure how this can be fixed otherwise, without swallowing an error that is. I don't really use dependabot much.

**Comment by danopia** [comment]
So I have Dependabot properly authenticated to my registry already with YAML like this:

```yaml
registries:
    google-artifact-registry:
        type: npm-registry
        url: https://europe-west1-npm.pkg.dev/my-project/npm-virtual/
        username: _json_key_base64
        password: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY_BASE64 }}'

version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      registries:
          - google-artifact-registry
      # [.. more config ..]
```

The problem seems to be that when using Yarn Berry with this plugin, Dependabot's attempts to update the lockfile by running `yarn` result in a plugin error and thus no PR is created. I'm not actually sure how Dependabot configures Yarn but it does manage it.

I also agree that swallowing the error is bad. I don't know much about Yarn Berry plugins but maybe there's a way to log a proper warning when `gcloud` isn't available? Then the wording can be improved as well, without throwing a plugin error.

We've been enjoying the workflow of this plugin on laptops and also password-free CI jobs. I have to admit though that dependabot has been a sticking point with getting my team set up on Google Artifact Registry. Even the above YAML took some trial & error haha
